# This workflow is triggered on pushes to the repository.

name: Mod Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Old package cleanup with Delete Package Versions
        uses: actions/delete-package-versions@v1
        with:
          package-name: 'minefantasy.mfr.MineFantasyReborn.MineFantasy-reborn'
          num-old-versions-to-delete: 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate build number
        uses: einaregilsson/build-number@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew setupCIWorkspace
          ./gradlew build
      - name: Publish to Github Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_API_KEY: ${{ secrets.GPR_TOKEN }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew setupCIWorkspace
          ./gradlew build publish